# Landing page config for /storefront/
# Inherits from root but OVERRIDES plugins to remove redirects
INHERIT: ../mkdocs.yml

theme:
    custom_dir: ../overrides

docs_dir: docs

# Project information
extra_site_name: Documentation
site_name: storefront
site_description: Frontend application documentation center
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/storefront

# Repository
repo_name: VirtoCommerce/vc-theme-b2b-vue
repo_url: https://github.com/VirtoCommerce/vc-theme-b2b-vue
edit_uri: edit/dev/docs/

# OVERRIDE plugins - NO redirects, NO monorepo!
plugins:
    - search

# Only build index.md
nav:
    - Home: index.md

extra:
    main_page:
        documentation:
            - title: User Guide
              link: user-guide/latest
              image: assets/images/storefront-userquide.png
              description:
                - title: Getting Started
                  link: https://youtu.be/xsnds1QYuC0
                - title: User Documentation
                  link: user-guide/latest/
                - title: Public Demo Environment
                  link: https://virtostart-demo-store.govirto.com/
            - title: Developer Guide
              link: developer-guide/latest
              image: assets/images/storefront-devguide.png
              description:
                - title: Overview
                  link: developer-guide/latest/
                - title: Architecture
                  link: developer-guide/latest/architecture
                - title: Deployment
                  link: developer-guide/latest/deployment
                - title: Integrations
                  link: developer-guide/latest/integrations/prerender_io
            - title: Other Resources
              image: assets/images/storefront-other.png
              description:
                - title: Release Notes
                  link: https://github.com/VirtoCommerce/vc-storefront/releases
                - title: Github
                  link: https://github.com/VirtoCommerce/vc-storefront/
        release_notes:
            - title: January 2026
              link: https://www.virtocommerce.org/t/virto-s-release-notes-january-2026/821
              type: Release Notes
              date: 1 January 2026
            - title: December 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-december-2025/818
              type: Release Notes
              date: 2 December 2025
            - title: November 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-november-2025/814
              type: Release Notes
              date: 6 November 2025
            - title: October 2025
              link: https://www.virtocommerce.org/t/virtos-release-notes-october-2025/807
              type: Release Notes
              date: 7 October 2025
            - title: September 2025
              link: https://www.virtocommerce.org/t/virtos-release-notes-september-2025/805
              type: Release Notes
              date: 2 September 2025
            - title: August 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-august-2025/801
              type: Release Notes
              date: 1 August 2025
            - title: July 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-july-2025/798
              type: Release Notes
              date: 7 July 2025
            - title: June 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-june-2025/796
              type: Release Notes
              date: 4 June 2025
            - title: May 2025
              link: https://www.virtocommerce.org/t/virtos-release-notes-may-2025/778
              type: Release Notes
              date: 1 May 2025
            - title: April 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-april-2025/769
              type: Release Notes
              date: 2 April 2025
            - title: March 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-march-2025/767
              type: Release Notes
              date: 3 March 2025
            - title: February 2025
              link: https://www.virtocommerce.org/t/virtos-release-notes-february-2025/760
              type: Release Notes
              date: 3 February 2025
            - title: January 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-january-2025/755
              type: Release Notes
              date: 1 January 2025
        link_cards:
            - title: Contact support
              icon: assets/icons/contact-support.svg
              link: https://help.virtocommerce.com/support/home
              outlineColor: "#EA534A"
            - title: Community
              icon: assets/icons/community.svg
              link: https://www.virtocommerce.org/
              outlineColor: "#EA534A"
            - title: GitHub
              icon: assets/icons/github-outline.svg
              link: https://github.com/VirtoCommerce
              outlineColor: "#FF9162"
            - title: Blog
              icon: assets/icons/blog.svg
              link: https://virtocommerce.com/blog
              outlineColor: "#FF9162"
