INHERIT: ../mkdocs.yml
theme:
    custom_dir: ../overrides


# Project information
extra_site_name: Documentation
site_name: platform
site_description: Platform documentation center
site_author: Virto Commerce
site_url: https://docs.virtocommerce.org/platform

# Repository
repo_name: VirtoCommerce/vc-platform
repo_url: https://github.com/VirtoCommerce/vc-platform
edit_uri: edit/dev/docs/

extra:
    main_page:
        documentation:
            - title: User Guide
              image: assets/images/storefront-userquide.png
              link: user-guide
              description:
                - title: Getting Started
                  link: user-guide/getting-started
                - title: User Documentation
                  link: user-guide
                - title: Versions
                  link: user-guide/versions/virto3-products-versions
                - title: Deployment of Environments on Virto Cloud
                  link: deployment-on-cloud/deploy-on-virto-cloud
            - title: Developer Guide
              image: assets/images/storefront-devguide.png
              link: developer-guide
              description:
                - title: Installation Guide
                  link: developer-guide/Getting-Started/Installation-Guide/windows
                - title: Architecture Overview
                  link: developer-guide/Back-End-Architecture/02-conceptual-overview
                - title: Extensibility
                  link: developer-guide/Extensibility/overview
                - title: Configuration reference
                  link: developer-guide/Configuration-Reference/appsettingsjson
                - title: Tutorials and How-tos
                  link: developer-guide/Tutorials-and-How-tos/Tutorials/creating-custom-module
                - title: REST API Reference
                  link: https://virtostart-demo-admin.govirto.com/docs/index.html
                - title: GraphQL API Reference
                  link: developer-guide/GraphQL-Storefront-API-Reference-xAPI/getting-started
            - title: Other Resources
              image: assets/images/storefront-other.png
              description:
                - title: Release Notes
                  link: https://github.com/VirtoCommerce/vc-platform/releases
                - title: Github
                  link: https://github.com/VirtoCommerce/vc-platform/
        release_notes:
            - title: February 2025
              link: https://www.virtocommerce.org/t/virtos-release-notes-february-2025/760
              type: Release Notes
              date: 3 February 2025
            - title: January 2025
              link: https://www.virtocommerce.org/t/virto-s-release-notes-january-2025/755
              type: Release Notes
              date: 1 January 2025
            - title: December 2024
              link: https://www.virtocommerce.org/t/virtos-release-notes-december-2024/747
              type: Release Notes
              date: 3 December 2024
            - title: November 2024
              link: https://www.virtocommerce.org/t/november-2024-news-digest/743
              type: Release Notes
              date: 1 November 2024
            - title: October 2024
              link: https://www.virtocommerce.org/t/october-2024-news-digest/734
              type: Release Notes
              date: 1 October 2024
            - title: September 2024
              link: https://www.virtocommerce.org/t/september-2024-news-digest/730
              type: Release Notes
              date: 9 September 2024
            - title: August 2024
              link: https://www.virtocommerce.org/t/august-2024-new-digest/719
              type: Release Notes
              date: 1 August 2024
            - title: July 2024
              link: https://www.virtocommerce.org/t/july-2024-news-digest/713
              type: Release Notes
              date: 1 July 2024
            - title: June 2024
              link: https://www.virtocommerce.org/t/june-2024-news-digest/702
              type: Release Notes
              date: 1 June 2024
            - title: May 2024
              link: https://www.virtocommerce.org/t/may-2024-news-digest/699
              type: Release Notes
              date: 2 May 2024
            - title: April 2024
              link: https://www.virtocommerce.org/t/april-2024-news-digest/689
              type: Release Notes
              date: 3 April 2024
            - title: March 2024
              link: https://www.virtocommerce.org/t/march-2024-news-digest/681
              type: Release Notes
              date: 5 March 2024
            - title: February 2024
              link: https://www.virtocommerce.org/t/february-2024-news-digest/673
              type: Release Notes
              date: 7 February 2024
            - title: January 2024
              link: https://www.virtocommerce.org/t/news-digest-january-2024/663
              type: Release Notes
              date: 8 January 2024
        link_cards:
                - title: Contact support
                  icon: assets/icons/contact-support.svg
                  link: https://help.virtocommerce.com/support/home
                  outlineColor: '#EA534A'
                - title: Community
                  icon: assets/icons/community.svg
                  link: https://www.virtocommerce.org/
                  outlineColor: '#EA534A'
                - title: GitHub
                  icon: assets/icons/github-outline.svg
                  link: https://github.com/VirtoCommerce
                  outlineColor: '#FF9162'
                - title: Blog
                  icon: assets/icons/blog.svg
                  link: https://vrtocommerce.com/blog
                  outlineColor: '#FF9162'
                - title: Versions
                  icon: assets/icons/version-icon.svg
                  link: https://github.com/VirtoCommerce/vc-platform/tree/dev/docs/products
                  outlineColor: '#FF9162'

nav:
    - Home: index.md
  # - Developer Guide: "!include ./developer-guide/mkdocs.yml"
  # - User Guide: "!include ./user-guide/mkdocs.yml"

